### ISSUE TITLE
有一个语句似乎多了个空格导致语句无效

### ISSUE THREAD

**Issue by ginnnnnncc** [Bmaili/NEU_health_daka#1]
run.py文件中第28行的正则表达式'\/tpass\/login[^\"] *'，'*' 前多了个' '，导致无法正确获取jsessionid及其后面的字符，只匹配到了"/tpass/login;"。
但能成功打卡。

**Comment by Bmaili** [comment]
确实多加了个空格，感谢指正，已修改~
因为requests库session对象能携带cookie，所以即便未显示地在url后添加jsessionid也是可以的^_^
