### ISSUE TITLE
体温打卡419报错

### ISSUE THREAD

**Issue by YoghurtGuy** [Bmaili/NEU_health_daka#4]
这个有啥办法解决一下吗？是只有我有这个问题吗

**Comment by Bmaili** [comment]
暂时没遇见过这个问题，能详细描述一下嘛

**Comment by YoghurtGuy** [comment]
刚刚已经解决，正在打字收到了大佬Bmaili的回复

原因是我只调用了登录(login)和体温打卡(temperatureDaka)函数，想要早中晚打卡时不必再次健康上报，

而self.token在健康上报（healthDaka）函数里才被赋值，没有token导致419错误，

通过将self.token的赋值语句移到了login函数里得以解决，



此外，我发现发送信息的时间为腾讯服务器的UTC时间，

```python
time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(time.time()+8*60*60))
```

我把他改成了获取UTC时间，但在当前时间的基础上加8小时（8x60x60秒）可以获得北京时间，同理，在判断体温打卡次数时的hour也修改为获取UTC时间+8，这样无论在腾讯服务器还是自己的设备上都可以得到正确的北京小时

```python
hour = (time.gmtime().tm_hour + 8) % 24
```
